### ISSUE TITLE
RCHGetElement #13892 is wrong

### ISSUE THREAD

**Issue by ClimberMel** [ClimberMel/SMF_Add-in#31]
Element# 13892 should be Forward P/E from Zacks (smf-elements-6.txt)

Here is where the Forward P/E comes from:
https://www.zacks.com/stock/quote/AAPL?q=AAPL
Here is the page section and if you search for Forward PE, then the following <dd></dd> tag contains the amount (28.76)
<section id="stock_key_earnings">
            <h3>Key Earnings Data</h3>
           
           <dl class="abut_bottom">
     
        <dt class="alpha"><a class="newwin" href="/earnings/earnings-surprise-predictions/">Earnings ESP</a>
            <div class="tooltip-wrapper"><button class="tt-trigger" rel="key_earnings_esp_data" aria-expanded="false" tt-init="true"><span class="info-tooltip" aria-hidden="true"></span><span class="sr-only">More Info</span></button></div>
            <div class="tooltiptext hide" id="key_earnings_esp_data">
            <p>Zacks Earnings ESP (Expected Surprise Prediction) looks to find companies that have recently seen positive earnings estimate revision activity. The idea is that more recent information is, generally speaking, more accurate and can be a better predictor of the future, which can give investors an advantage in earnings season.</p>
    <p>The technique has proven to be very useful for finding positive surprises. In fact, when combining a Zacks Rank #3 or better and a positive Earnings ESP, stocks produced a positive surprise 70% of the time, while they also saw 28.3% annual returns on average, according to our 10 year backtest.
    </p>
    <p><a href="//www.zacks.com/earnings/earnings-surprise-predictions/">Visit the Earnings ESP Center</a></p>
    <p class="premium"><a href="//www.zacks.com/premium/esp-buy?adid=zp_esptooltip&amp;icid=zpi_esptooltip">See the Full List of Stocks To Beat Earnings</a></p>
            </div>
        </dt>
        <dd class="">0.00%</dd>
      </dl>
      <dl class="abut_bottom">  
        <dt class="alpha"><a class="newwin" href="/stock/quote/AAPL/detailed-estimates">Most Accurate Est</a></dt>
        <dd>1.17</dd>
       
      </dl>
       <dl class="abut_bottom">  
        <dt class="alpha"><a class="newwin" href="/stock/quote/AAPL/detailed-estimates">Current Qtr Est</a></dt>
        <dd>1.17</dd>
       
      </dl>
       <dl class="abut_bottom">  
        <dt class="alpha"><a class="newwin" href="/stock/quote/AAPL/detailed-estimates">Current Yr Est</a></dt>
        <dd>6.03</dd>
       
      </dl>
      <dl class="abut_bottom">  
        <dt class="alpha position_relative">
        <a class="newwin" href="/stock/research/AAPL/earnings-announcements">Exp Earnings Date</a>
            <div class="tooltip-wrapper"><button class="tt-trigger" rel="exp_earning_date_pop" aria-expanded="false" tt-init="true"><span class="info-tooltip " aria-hidden="true"></span><span class="sr-only">More Info</span></button></div>
            <div class="tooltiptext hide" id="exp_earning_date_pop">
                <p>This is an estimated date of earnings release. Neither Zacks Investment
                Research, Inc. nor its Information Providers can guarantee the accuracy,
                completeness, timeliness, or correct sequencing of any of the Information on
                the Web site, including, but not limited to Information originated by Zacks
                Investment Research, Inc, licensed by Zacks Investment Research, Inc. from
                Information Providers, or gathered by Zacks Investment Research, Inc. from
                publicly available sources. There may be delays, omissions, or inaccuracies
                in the Information.</p>
            </div>
        </dt>
        <dd><sup class="spl_sup_text"></sup>7/27/23</dd>
       
      </dl>

       <dl class="abut_bottom">  
        <dt class="alpha">Prior Year EPS</dt>
        <dd>6.11</dd>
       
      </dl>
          <dl class="abut_bottom">  
        <dt class="alpha"><a class="newwin" href="/stock/quote/AAPL/detailed-estimates">Exp EPS Growth <span class="year">(3-5yr)</span></a></dt>
        <dd><p class="up float_right">12.50%</p></dd>
       
      </dl>
     <dl class="abut_bottom">  
        <dt class="alpha"><a class="newwin" href="/stock/chart/AAPL/fundamental/pe-ratio-ttm">Forward PE</a></dt>
        <dd>28.76</dd>
       
      </dl>    
      <dl class="abut_bottom">  
        <dt class="alpha"><a class="newwin" href="/stock/chart/AAPL/fundamental/peg-ratio-ttm">PEG Ratio</a></dt>
        <dd>2.30</dd>
       
      </dl>    
         
    </section>

**Comment by ClimberMel** [comment]
From Ian:
A direct way to get the Zacks forward PE is to get it from that page:
RCHGetTableCell("https://www.zacks.com/stock/quote/AAPL/detailed-earning-estimates",1,"P/E (F1)",1)

Ian

**Comment by ClimberMel** [comment]
So since it works the way Ian posted, it should be a fixable in RCHGetElement

**Comment by kitiany** [comment]
Tested editing smf-elements-6.txt line to:
13892;Zacks;Forward P/E;=RCHGetTableCell("https://www.zacks.com/stock/quote/~~~~~/detailed-earning-estimates",1,">P/E (F1)")
Restarted Excel and it works.

**Comment by ClimberMel** [comment]
Although the suggested change above did work, I decided make a fix that allowed getting the data from the quote page as it did originally instead of the detailed-earning-estimates page.
Updated smf-elements-6.txt.

**Comment by kitiany** [comment]
Mel, I see an error in your update.
13892;Zacks;Forward P/E;=smfGetTagContent("https://www.zacks.com/stock/quote/AAPL","dd",1,">Forward PE")
~~~~~ needs to replace "AAPL"
Ian

**Comment by ClimberMel** [comment]
What is the error?

**Comment by kitiany** [comment]
It is hard coded to AAPL and not 5 squiggly marks used as the variable.

**Comment by ClimberMel** [comment]
Oh silly me, I do that during testing... I'll send a new one out,  Thanks!
