### ISSUE TITLE
RCHGetElement #848 is wrong

### ISSUE THREAD

**Issue by kitiany** [ClimberMel/SMF_Add-in#32]
sjagers reported Element number 848 used to return Zacks Rank, but now I get an Error.
mff3429 suggested this change:
=TRIM(smfStrExtr(RCHGetWebData("https://www.zacks.com/stock/quote/~~~~~/financial-overview","rank_view",600),"rank_view"">","<span"))
It does work. To return to the original output of just a number, I tested this edit.
848;Zacks;Zacks Rank;=TRIM(smfStrExtr(RCHGetWebData("https://www.zacks.com/stock/quote/~~~~~/financial-overview","rank_view",600),"rank_view"">","-"))
It seems to work.

**Comment by ClimberMel** [comment]
I'm going to see if I can fix the element files to fix a few of these.

**Comment by ClimberMel** [comment]
Fixed in recent release.  Required a code change to smfGetTagContent to process scraping from <span> tag as well as updating element 848 in smf-elements-6.txt.
