### ISSUE TITLE
Items 27 & 28 incorrect in smf-elements-1.txt

### ISSUE THREAD

**Issue by Bruce-95** [ClimberMel/SMF_Add-in#41]
Line items in smf-elements-1.txt 

27;YahooFD;Mean Target Price;=smfGetYahooJSONData(ticker,"financialData","targetMeanPrice")
28;YahooFD;Revenue;=smfGetYahooJSONData(ticker,"financialData","totalRevenue")

should be

27;YahooFD;Mean Target Price;=smfGetYahooJSONData("~~~~~","financialData","targetMeanPrice")
28;YahooFD;Revenue;=smfGetYahooJSONData("~~~~~","financialData","totalRevenue")

**Comment by ClimberMel** [comment]
Corrected these and a number of other ones.  I had ticker defined as a name in my test sheet and missed changing it back when updating the elements file.
