### ISSUE TITLE
smf-element-1.txt elements 27 and 28 typo?

### ISSUE THREAD

**Issue by joeyiii57** [ClimberMel/SMF_Add-in#43]
smf-element-1.txt  in the Docs folder still has "ticker" instead of "~~~~~" for these two elements
27;YahooFD;Mean Target Price;=smfGetYahooJSONData(ticker,"financialData","targetMeanPrice")
28;YahooFD;Revenue;=smfGetYahooJSONData(ticker,"financialData","totalRevenue")

**Comment by ClimberMel** [comment]
These have been corrected
