### ISSUE TITLE
smf-elements-1.txt file from RCH_Stock_Market_Functions-3.0.2023.06.05.zip  has 7 errors

### ISSUE THREAD

**Issue by Bruce-95** [ClimberMel/SMF_Add-in#44]
.
Hi Mel,

I downloaded RCH_Stock_Market_Functions-3.0.2023.06.05.zip at 12:52 pm PST today. As others have reported the "smf-elements-1.txt" file still shows "ticker" in the 1st parameter instead of "~~~~~" in the following line items -

18;YahooPrice;Open;=smfGetYahooJSONData(ticker,"price","regularMarketOpen")
19;YahooPrice;High;=smfGetYahooJSONData(ticker,"price","regularMarketDayHigh")
20;YahooPrice;Low;=smfGetYahooJSONData(ticker,"price","regularMarketDayLow")
21;YahooPrice;Volume;=smfGetYahooJSONData(ticker,"price","regularMarketVolume")
27;YahooFD;Mean Target Price;=smfGetYahooJSONData(ticker,"financialData","targetMeanPrice")
28;YahooFD;Revenue;=smfGetYahooJSONData(ticker,"financialData","totalRevenue")
45;YahooFD;EBITDA;=smfGetYahooJSONData(ticker,"financialData","ebitda")

Also the "Elements" portion of the web site (https://climbermel.github.io/SMF_Add-in --> Elements --> smf-elements-1.txt) also shows the "ticker" parameter.

Just wanted to officially get this on your to-do list.

~ Bruce

**Comment by Bruce-95** [comment]
Partial duplicate of issue #43 .

**Comment by ClimberMel** [comment]
These have been corrected.
