### ISSUE TITLE
Documentation - missing/updated docs attached

### ISSUE THREAD

**Issue by Bruce-95** [ClimberMel/SMF_Add-in#45]
Hi Mel, 
attached is a zip file containing htm files (see below) for functions that were missing.  Sorry but I used MS Word to save the docs as htm files so there's going to be bloat. There's also a $$Read Me file that has info on fixing other links on the Documentation page.

- smfGetYahooJSONData-Function().htm - (updated) 
- smfStrExtr()-Function.htm - (updated) 
- smfGetYahooPortfolioView()-Function.htm - (was missing)
- smfPricesBetween-Function.htm - - (was missing)
- smfForceRecalculation-Macro.htm - - (was missing)
- smfWord-Function.htm - - (was missing)

Let me know if you seen any problems. And absolutely feel free to modify the content of the documents as you see fit.

~ Bruce S

[New SMF docs (06.09.23).zip](https://github.com/ClimberMel/SMF_Add-in/files/11710770/New.SMF.docs.06.09.23.zip)

**Comment by Bruce-95** [comment]
This overrides issue #38

**Comment by Bruce-95** [comment]
Mel,

I noticed a couple of typo's in 2 docs I sent yesterday. See attached. Sorry about that.

~ Bruce S

[Updated SMF docs (06.10.23).zip](https://github.com/ClimberMel/SMF_Add-in/files/11713501/Updated.SMF.docs.06.10.23.zip)

**Comment by ClimberMel** [comment]
I updated these but never closed the ticket...
