### ISSUE TITLE
smfWord() Documentation error

### ISSUE THREAD

**Issue by Bruce-95** [ClimberMel/SMF_Add-in#48]
Hi Mel,

Re the documentation for smfWord() from the Documentation page, the first smfWord() example left off a couple of parameters. It shows this -
".... you would use: =smfWord("apples - oranges - bananas - grapes") ... which gives bananas ....."

It should show this:
".... you would use:  =smfWord("apples - oranges - bananas - grapes", "3", "-")  ... which gives “ bananas “ ..... "

~ Bruce S

**Comment by ClimberMel** [comment]
Completed but never closed
