### ISSUE TITLE
Update Elements 13865 and 13867  in smf-elements-2.txt

### ISSUE THREAD

**Issue by Bruce-95** [ClimberMel/SMF_Add-in#52]
These 2 elements now require "crumb" processing. See attached for updated elements.

[Updated YahooIN elements.txt](https://github.com/ClimberMel/SMF_Add-in/files/12137409/Updated.YahooIN.elements.txt)

**Comment by ClimberMel** [comment]
Merged with #55 which includes numerous changed to elements2.txt

**Comment by ClimberMel** [comment]
Will be included in coming release
