### ISSUE TITLE
Release RCH_Stock_Market_Functions-3.0.2023.07.25

### ISSUE THREAD

**Issue by ClimberMel** [ClimberMel/SMF_Add-in#53]
Contains fix to smfGetYahooJSONData
Changes to smf-elements-1.txt and smf-elements-2.txt

**Comment by ClimberMel** [comment]
Cancel changes to RCH_Stock_Market_Functions as Yahoo has switched changes back and all is working now.  Still need to release new Elements.

**Comment by marquiskissel** [comment]
How do we download this update? I don't see it on https://climbermel.github.io/SMF_Add-in/ and I seem to no longer have access to the google group comments. As always, I really appreciate all the time and effort you put into this!

**Comment by ClimberMel** [comment]
I didn't create that one since Yahoo started working again.  I need to finish up the element files and post those.MelSent from my Galaxy
-------- Original message --------From: marquiskissel ***@***.***> Date: 2023-08-07  11:28 a.m.  (GMT-08:00) To: ClimberMel/SMF_Add-in ***@***.***> Cc: ClimberMel ***@***.***>, Author ***@***.***> Subject: Re: [ClimberMel/SMF_Add-in] Release RCH_Stock_Market_Functions-3.0.2023.07.25 (Issue #53) 
How do we download this update? I don't see it on https://climbermel.github.io/SMF_Add-in/ and I seem to no longer have access to the google group comments. As always, I really appreciate all the time and effort you put into this!

**Comment by ClimberMel** [comment]
Added elements files to next release
