### ISSUE TITLE
Change smfGetYahooJSONField() function to get data using "crumb" code

### ISSUE THREAD

**Issue by Bruce-95** [ClimberMel/SMF_Add-in#55]
People are posting saying they are not getting data for some elements. Many of these elements are in the smf-elements-2.txt file using the smfGetYahooJSONField() function. Currently the function is trying to get url data without the "crumb" code.

Near the end of the smfGetYahooJSONField() function in the modGetYahooJSONData module, please change 

......... s1 = smfGetWebPage(sURL)
to ... s1 = smfGetWebPage(sURL, 4)

**Comment by ClimberMel** [comment]
Bruce can you create a spreadsheet with all the elements from elements2.txt, then make any of the changes and forward the file here?  I can then post it for everyone.

**Comment by Bruce-95** [comment]
As requested here's the updated smf-elements-2.txt and a spreadsheet containing all those elements . And yes the update includes those reported in issue #52. (The spreadsheet I sent you earlier was one I used for testing issue #56. My bad. )

[smf-elements-2.txt](https://github.com/ClimberMel/SMF_Add-in/files/12491821/smf-elements-2.txt)
[smf-elements-2.xlsx](https://github.com/ClimberMel/SMF_Add-in/files/12491822/smf-elements-2.xlsx)

**Comment by ClimberMel** [comment]
Adding to new release
