### ISSUE TITLE
Updated code attached to allow Excel x64 to emulate =smfGetYahooJSONField

### ISSUE THREAD

**Issue by Bruce-95** [ClimberMel/SMF_Add-in#56]
Since =smfGetYahooJSONField only worked on Excel x32 because of ScriptEngine, another alternative was needed for Excel x64. 

Attached are 2 updated modules and 1 new module that emulates the JScript processing for Excel x64.

[Updated smfGetYahooJSONField.zip](https://github.com/ClimberMel/SMF_Add-in/files/12480908/Updated.smfGetYahooJSONField.zip)

**Comment by ClimberMel** [comment]
Testing on Excel 2010 64bit...
