### ISSUE TITLE
Enhancement : Exchange rate functions ?

### ISSUE THREAD

**Issue by DaveInDev** [ClimberMel/SMF_Add-in#60]
Hi,
first, thanks for this very nice addin.

As some of us may trade in various currencies, it would be nice to be able to download currency data from the web (current exchange rate, but also historical values)..

Data available here for example
https://finance.yahoo.com/quote/EURUSD%3DX/history?p=EURUSD%3DX

**Comment by ClimberMel** [comment]
Works fine with smfGetYahooHistory.xlsx just put in the symbol EURUSD%3DX for the ticker
