### ISSUE TITLE
Need new Element numbers for Yahoo Balance Sheet data

### ISSUE THREAD

**Issue by Bruce-95** [ClimberMel/SMF_Add-in#72]
Hi Mel,

I found the JSON file(s) for Yahoo's annual AND quarterly Balance Sheet data. I'll need about 300 new element nbrs. Do you want to assign them to me or can I get them from unassigned nbrs in [RCHGetElementNumber-Element-Definitions.xlsx](https://climbermel.github.io/SMF_Add-in/samples/RCHGetElementNumber-Element-Definitions.xlsx) assuming it's up to date?

The JSON data comes from a new url so there's going to be some coding changes too.

Right now I'm building the "json" arguments then I'll start testing them.

~ Bruce S

**Comment by ClimberMel** [comment]
I have a quick look and let you know.  I have been trying to keep the numbering logical (at least to me)  😀Sent from my Galaxy
-------- Original message --------From: Bruce S ***@***.***> Date: 2024-05-26  1:18 p.m.  (GMT-08:00) To: ClimberMel/SMF_Add-in ***@***.***> Cc: Subscribed ***@***.***> Subject: [ClimberMel/SMF_Add-in] Need new Element numbers for Yahoo Balance Sheet data (Issue #72) 
Hi Mel,
I found the JSON file(s) for Yahoo's annual AND quarterly Balance Sheet data. I'll need about 300 new element nbrs. Do you want to assign them to me or can I get them from unassigned nbrs in RCHGetElementNumber-Element-Definitions.xlsx assuming it's up to date?
The JSON data comes from a new url so there's going to be some coding changes too.
Right now I'm building the "json" arguments then I'll start testing them.
~ Bruce S

**Comment by ClimberMel** [comment]
Use smf-elements-1.txt
It is YPV up to 91 then nothing until 541 for StockScouter.  So lots of room there.
If those are existing codes that no longer work... do you think we should just replace the code and keep the numbers?

**Comment by Bruce-95** [comment]
Okay on using 100-499.

_If those are existing codes that no longer work... do you think we should just replace the code and keep the numbers?_

Not sure what "existing codes" you mean.

**Comment by Bruce-95** [comment]
Hi Mel,

Re the Balance Sheet data - I'm going to need some guidance on what data to return. If you look at the [balance sheet url](https://finance.yahoo.com/quote/IBM/balance-sheet) for IBM and hit the "Expand All" button above and to the right of the headings, you'll see there's 89 quarterly fields and 89 annual fields. Some stocks have more, some less, ex; CAVA has 59 BS fields. .

Each field has 9 data points/elements - 5 quarters plus 4 years - so I'd have to define 801 elements (89 * 9) which isn't feasible. 

I've attached a spreadsheet showing the quarterly and annual Balance Sheet (BS) fields returned for IBM. I've "X"ed some fields that I thought might be returned but I personally don't use balance sheet info so I don't know what would be "must haves" by the members. I think 20 fields (180 elements) is the absolute limit, 15 fields (135 elements) would be better, less more so.

Would you look at the spreadsheet, "X" the ones you think we need and send it back to me? Thanks.

~ Bruce S

[(Test) Yahoo Balance Sheet fields.xlsx](https://github.com/ClimberMel/SMF_Add-in/files/15473562/Test.Yahoo.Balance.Sheet.fields.xlsx)

**Comment by ClimberMel** [comment]
Slogging through these... this is not data I pull from Yahoo either.  I can get all fundamentals via my broker API.

**Comment by Bruce-95** [comment]
Hi Mel,

Attached are the updated element files and functions for release for Yahoo's new Balance Sheet and Income Statement JSON data. (Finally got this done.) Let me know if there are any questions.

~ Bruce S

[GetJSONData.zip](https://github.com/user-attachments/files/15811937/GetJSONData.zip)

**Comment by ClimberMel** [comment]
Awesome.  Thanks.  Do you happen to use python?MelSent from my Galaxy
-------- Original message --------From: Bruce S ***@***.***> Date: 2024-06-12  4:29 p.m.  (GMT-08:00) To: ClimberMel/SMF_Add-in ***@***.***> Cc: ClimberMel ***@***.***>, Comment ***@***.***> Subject: Re: [ClimberMel/SMF_Add-in] Need new Element numbers for Yahoo Balance Sheet data (Issue #72) 
Hi Mel,
Attached are the updated element files and functions for release for Yahoo's new Balance Sheet and Income Statement JSON data. (Finally got this done.) Let me know if there are any questions.
~ Bruce S
GetJSONData.zip

**Comment by Bruce-95** [comment]
No, never used Python - but it is on my bucket list. Just don't know when I can devote the time.
~ Bruce S

**Comment by ClimberMel** [comment]
I do mostly python programming these days.  I can get data live from my broker as well as yahoo using it.If you get into it let me know as I can show you lots of code to get started.MelSent from my Galaxy
-------- Original message --------From: Bruce S ***@***.***> Date: 2024-06-15  3:25 p.m.  (GMT-08:00) To: ClimberMel/SMF_Add-in ***@***.***> Cc: ClimberMel ***@***.***>, Comment ***@***.***> Subject: Re: [ClimberMel/SMF_Add-in] Need new Element numbers for Yahoo Balance Sheet data (Issue #72) 
No, never used Python - but it is on my bucket list. Just don't know when I can devote the time.
~ Bruce S

**Comment by Bruce-95** [comment]
Mel,

please use this version of modGetYahooJSONData in the BETA release. It was fixed to use the correct UTC time in the "time-series" url.

~ Bruce S

[modGetYahooJSONData- 06-19-2024.zip](https://github.com/user-attachments/files/15905378/modGetYahooJSONData-.06-19-2024.zip)

**Comment by Bruce-95** [comment]
Ok..... ABSOLUTELY final update for getting Yahoo's Balance Sheet and Income Statement data is attached and ready for release.

~ Bruce S

[modGetYahooJSONData- 07-01-2024.zip](https://github.com/user-attachments/files/16059752/modGetYahooJSONData-.07-01-2024.zip)

**Comment by ClimberMel** [comment]
Cool!  Heading home tomorrow, so should be able to bundle ot up latrr this week.Thanks,MelSent from my Galaxy
-------- Original message --------From: Bruce S ***@***.***> Date: 2024-07-01  4:15 p.m.  (GMT-08:00) To: ClimberMel/SMF_Add-in ***@***.***> Cc: ClimberMel ***@***.***>, Comment ***@***.***> Subject: Re: [ClimberMel/SMF_Add-in] Need new Element numbers for Yahoo Balance Sheet data (Issue #72) 
Ok..... ABSOLUTELY final update for getting Yahoo's Balance Sheet and Income Statement data is attached and ready for release.
~ Bruce S
modGetYahooJSONData- 07-01-2024.zip

**Comment by Bruce-95** [comment]
Off topic:  I noticed you made me a "collaborator" on SMF.  I'm not sure what that means. Maybe when you get back you can tell me what you want me to do and don't do on github. I'm assuming this will take some administrative work off your shoulders? I'm reading up on github as I get time.  I'm willing to help.

~ Bruce S

**Comment by ClimberMel** [comment]
I'm hoping to use GitHub properly where you could create a branch and make updates to that branch, then I review and approve and GH will merge the branches.  Saves double handling files where we can make mistakes.  I also need to read on gitattributes to see how to make files conform to correct formatting.Thanks,MelSent from my Galaxy
-------- Original message --------From: Bruce S ***@***.***> Date: 2024-07-01  5:39 p.m.  (GMT-08:00) To: ClimberMel/SMF_Add-in ***@***.***> Cc: ClimberMel ***@***.***>, Comment ***@***.***> Subject: Re: [ClimberMel/SMF_Add-in] Need new Element numbers for Yahoo Balance Sheet data (Issue #72) 
Off topic:  I noticed you made me a "collaborator" on SMF.  I'm not sure what that means. Maybe when you get back you can tell me what you want me to do and don't do on github. I'm assuming this will take some administrative work off your shoulders? I'm reading up on github as I get time.  I'm willing to help.
~ Bruce S
